### ISSUE TITLE
.rate .furryify .rps commands

### ISSUE THREAD

**Issue by catvvvv** [Xiahomielol/Crack-Bot#15]
Funny commands:
Rock paper scissors
rate some message from 1 to 10
transform messages to furry speak like replacing r with w or idk
if someone tries to send fuck you as command the bot will reply with no

**Comment by Xiahomielol** [comment]
I will happily do *most* of these things. I'm still not sure about the furry speech one but alllright

**Comment by Xiahomielol** [comment]
What I will make:

* .furryify
* .rate

What I won't make:
.rps (rock paper scissors)
