### ISSUE TITLE
improve .furryify command

### ISSUE THREAD

**Issue by catvvvv** [Xiahomielol/Crack-Bot#17]
we like to twoww we do a little twowwing
[no] => [nyo]
[l] => [w]
[th] => [ff]

too much trowwing is bewow
[u] => [uwu]
[o] => [owo

https://user-images.githubusercontent.com/97743795/149562456-db13cb72-d7d9-4479-9a61-dcaa7ddba1ac.mp4

]

**Comment by Xiahomielol** [comment]
Added the following instructions

Replace no => nyo
Replace L => w
